version: '3'
services:
  docker-postgresql:
    restart: always
    container_name: docker-postgresql
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  sport-meeting-point:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: postgres:5432
    depends_on:
      - docker-postgresql